# Generated by Django 4.0.1 on 2022-02-07 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteerName', models.CharField(max_length=20)),
                ('volunteerGender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, null=True)),
                ('volunteerPhone', models.IntegerField()),
                ('volunteerEmail', models.EmailField(max_length=254)),
                ('volunteerAddress', models.TextField(default=None)),
                ('volunteerImage', models.ImageField(upload_to='volunteers')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=20)),
                ('donorGender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20)),
                ('donorPhone', models.IntegerField()),
                ('donorEmail', models.EmailField(max_length=254)),
                ('donorAddress', models.TextField(default=None)),
                ('donorAvatar', models.ImageField(upload_to='donor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
