# Generated by Django 4.0.1 on 2022-02-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donorAddress',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorAvatar',
            field=models.ImageField(null=True, upload_to='donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorGender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorPhone',
            field=models.IntegerField(null=True),
        ),
    ]
