# Generated by Django 4.0.1 on 2022-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_donor_donoraddress_alter_donor_donoravatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=40)),
                ('orgOwnerName', models.CharField(max_length=20)),
                ('orgPhone', models.CharField(max_length=11)),
                ('orgEmail', models.EmailField(max_length=254)),
                ('orgAddress', models.TextField(default=None)),
                ('orgDescription', models.TextField(default='')),
                ('orgDocument', models.ImageField(upload_to='Verifications')),
            ],
        ),
    ]
