# Generated by Django 4.0.1 on 2022-02-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0004_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Zakatrecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientName', models.CharField(max_length=20, null=True)),
                ('recipientGender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, null=True)),
                ('recipientPhone', models.IntegerField(null=True)),
                ('recipientEmail', models.EmailField(max_length=254, null=True)),
                ('recipientAddress', models.TextField(default=None, null=True)),
                ('recipientAvatar', models.ImageField(null=True, upload_to='donor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
