# Generated by Django 3.2.12 on 2022-02-21 10:41

from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0005_alter_donor_user_zakatrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterFirstName', models.CharField(default=None, max_length=30, null=True)),
                ('requesterLastName', models.CharField(default=None, max_length=30, null=True)),
                ('requesterAddress', models.TextField(default=None, null=True)),
                ('requesterCity', models.TextField(blank=True, default=None, null=True)),
                ('requesterZip', models.CharField(default=None, max_length=15, null=True)),
                ('requesterNID', models.CharField(default=None, max_length=15)),
                ('requestDescription', models.TextField(blank=True, default=None)),
                ('requestReason', models.CharField(choices=[('poor', 'Poor'), ('medicalEmergency', 'medical Emergency'), ('others', 'Others')], default=None, max_length=20)),
                ('requestDocument', models.ImageField(blank=True, default=None, null=True, upload_to='Verifications/')),
                ('requestedAmount', models.IntegerField(default=None)),
                ('user', models.ForeignKey(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, max_length=30, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Profile.donor')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=20)),
                ('projectTargetPrice', models.IntegerField()),
                ('projectDescriptions', models.TextField(default=None)),
                ('projectImage', models.ImageField(default='', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForDonation',
            fields=[
                ('donationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Donations.donationrequest')),
            ],
            bases=('Donations.donationrequest',),
        ),
        migrations.CreateModel(
            name='Zakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('zakatAmount', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date')),
                ('organizationZakat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('donationMoney', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date')),
                ('organizationDonation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.organization')),
                ('projectDonation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Donations.projectdonation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.donor')),
            ],
        ),
    ]
