# Generated by Django 3.2.12 on 2022-03-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0002_rename_organizationzakat_zakat_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestForDonation',
        ),
    ]
