# Generated by Django 3.2.12 on 2022-03-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0004_auto_20220321_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='zakat',
            name='date',
        ),
    ]
