# Generated by Django 3.2.12 on 2022-03-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_donor_user_zakatrecipient'),
        ('Donations', '0005_auto_20220321_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.donor'),
        ),
    ]
