# Generated by Django 3.2.12 on 2022-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donarName', models.CharField(max_length=20)),
                ('OrganizationName', models.CharField(max_length=20)),
                ('ProjectName', models.CharField(max_length=20)),
                ('recipientName', models.CharField(max_length=20)),
                ('recipientPhone', models.CharField(max_length=11)),
            ],
        ),
    ]
