# Generated by Django 3.2.12 on 2022-03-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0002_rename_organizationzakat_zakat_organization'),
        ('Profile', '0005_alter_donor_user_zakatrecipient'),
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackdonation',
            name='donarName',
        ),
        migrations.AddField(
            model_name='trackdonation',
            name='donorName',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Profile.donor'),
        ),
        migrations.AddField(
            model_name='trackdonation',
            name='recipientAddress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackdonation',
            name='OrganizationName',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Profile.organization'),
        ),
        migrations.AlterField(
            model_name='trackdonation',
            name='ProjectName',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Donations.projectdonation'),
        ),
        migrations.AlterField(
            model_name='trackdonation',
            name='recipientName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackdonation',
            name='recipientPhone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
