# Generated by Django 3.2.12 on 2022-03-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_auto_20220321_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackdonation',
            name='donotionAmount',
            field=models.FloatField(default=None),
        ),
    ]
