# Generated by Django 3.2.12 on 2022-03-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_donor_user_zakatrecipient'),
        ('Donations', '0002_rename_organizationzakat_zakat_organization'),
        ('Track', '0005_auto_20220321_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdonation',
            name='OrganizationName',
            field=models.ForeignKey(blank=True, default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Profile.organization'),
        ),
        migrations.AlterField(
            model_name='trackdonation',
            name='ProjectName',
            field=models.ForeignKey(blank=True, default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Donations.projectdonation'),
        ),
    ]
