# Generated by Django 3.2.12 on 2022-03-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0007_auto_20220321_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackdonation',
            name='recipientAvatar',
            field=models.ImageField(default='', upload_to='recipients/'),
        ),
    ]
