# Generated by Django 3.2.12 on 2022-03-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0008_trackdonation_recipientavatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackdonation',
            old_name='donotionAmount',
            new_name='recipeAmount',
        ),
        migrations.RemoveField(
            model_name='trackdonation',
            name='OrganizationName',
        ),
        migrations.RemoveField(
            model_name='trackdonation',
            name='ProjectName',
        ),
    ]
