# Generated by Django 3.2.12 on 2022-03-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0009_auto_20220322_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackdonation',
            old_name='recipeAmount',
            new_name='receiptAmount',
        ),
    ]
